name: CI Test — sanity

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'README.md'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print hello
        run: |
          echo "Hello — GitHub Actions is running!"
          echo "List .github/workflows:"
          ls -la .github/workflows || true
